-- Generated By protoc-gen-lua Do not Edit
-- source: net.proto
local protobuf = require "protobuf"

local LOGINREQ = protobuf.Descriptor();
local LOGINREQ_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local LOGINREQ_PASSWORD_FIELD = protobuf.FieldDescriptor();
local LOGINREQ_CHANNEL_FIELD = protobuf.FieldDescriptor();
local BATTLERESULT = protobuf.Descriptor();
local BATTLERESULT_HERO_ID_FIELD = protobuf.FieldDescriptor();
local BATTLERESULT_DAMAGE_FIELD = protobuf.FieldDescriptor();
local BATTLERESULT_WIN_FIELD = protobuf.FieldDescriptor();
local BATTLERESULT_DROP_ITEMS_FIELD = protobuf.FieldDescriptor();

LOGINREQ_ACCOUNT_FIELD.name = "account"
LOGINREQ_ACCOUNT_FIELD.full_name = ".net.LoginReq.account"
LOGINREQ_ACCOUNT_FIELD.number = 1
LOGINREQ_ACCOUNT_FIELD.index = 0
LOGINREQ_ACCOUNT_FIELD.label = 2
LOGINREQ_ACCOUNT_FIELD.has_default_value = false
LOGINREQ_ACCOUNT_FIELD.default_value = ""
LOGINREQ_ACCOUNT_FIELD.type = 9
LOGINREQ_ACCOUNT_FIELD.cpp_type = 9

LOGINREQ_PASSWORD_FIELD.name = "password"
LOGINREQ_PASSWORD_FIELD.full_name = ".net.LoginReq.password"
LOGINREQ_PASSWORD_FIELD.number = 2
LOGINREQ_PASSWORD_FIELD.index = 1
LOGINREQ_PASSWORD_FIELD.label = 2
LOGINREQ_PASSWORD_FIELD.has_default_value = false
LOGINREQ_PASSWORD_FIELD.default_value = ""
LOGINREQ_PASSWORD_FIELD.type = 9
LOGINREQ_PASSWORD_FIELD.cpp_type = 9

LOGINREQ_CHANNEL_FIELD.name = "channel"
LOGINREQ_CHANNEL_FIELD.full_name = ".net.LoginReq.channel"
LOGINREQ_CHANNEL_FIELD.number = 3
LOGINREQ_CHANNEL_FIELD.index = 2
LOGINREQ_CHANNEL_FIELD.label = 1
LOGINREQ_CHANNEL_FIELD.has_default_value = false
LOGINREQ_CHANNEL_FIELD.default_value = 0
LOGINREQ_CHANNEL_FIELD.type = 5
LOGINREQ_CHANNEL_FIELD.cpp_type = 1

LOGINREQ.name = "LoginReq"
LOGINREQ.full_name = ".net.LoginReq"
LOGINREQ.nested_types = {}
LOGINREQ.enum_types = {}
LOGINREQ.fields = {LOGINREQ_ACCOUNT_FIELD, LOGINREQ_PASSWORD_FIELD, LOGINREQ_CHANNEL_FIELD}
LOGINREQ.is_extendable = false
LOGINREQ.extensions = {}

BATTLERESULT_HERO_ID_FIELD.name = "hero_id"
BATTLERESULT_HERO_ID_FIELD.full_name = ".net.BattleResult.hero_id"
BATTLERESULT_HERO_ID_FIELD.number = 1
BATTLERESULT_HERO_ID_FIELD.index = 0
BATTLERESULT_HERO_ID_FIELD.label = 2
BATTLERESULT_HERO_ID_FIELD.has_default_value = false
BATTLERESULT_HERO_ID_FIELD.default_value = 0
BATTLERESULT_HERO_ID_FIELD.type = 5
BATTLERESULT_HERO_ID_FIELD.cpp_type = 1

BATTLERESULT_DAMAGE_FIELD.name = "damage"
BATTLERESULT_DAMAGE_FIELD.full_name = ".net.BattleResult.damage"
BATTLERESULT_DAMAGE_FIELD.number = 2
BATTLERESULT_DAMAGE_FIELD.index = 1
BATTLERESULT_DAMAGE_FIELD.label = 2
BATTLERESULT_DAMAGE_FIELD.has_default_value = false
BATTLERESULT_DAMAGE_FIELD.default_value = 0
BATTLERESULT_DAMAGE_FIELD.type = 5
BATTLERESULT_DAMAGE_FIELD.cpp_type = 1

BATTLERESULT_WIN_FIELD.name = "win"
BATTLERESULT_WIN_FIELD.full_name = ".net.BattleResult.win"
BATTLERESULT_WIN_FIELD.number = 3
BATTLERESULT_WIN_FIELD.index = 2
BATTLERESULT_WIN_FIELD.label = 2
BATTLERESULT_WIN_FIELD.has_default_value = false
BATTLERESULT_WIN_FIELD.default_value = false
BATTLERESULT_WIN_FIELD.type = 8
BATTLERESULT_WIN_FIELD.cpp_type = 7

BATTLERESULT_DROP_ITEMS_FIELD.name = "drop_items"
BATTLERESULT_DROP_ITEMS_FIELD.full_name = ".net.BattleResult.drop_items"
BATTLERESULT_DROP_ITEMS_FIELD.number = 4
BATTLERESULT_DROP_ITEMS_FIELD.index = 3
BATTLERESULT_DROP_ITEMS_FIELD.label = 3
BATTLERESULT_DROP_ITEMS_FIELD.has_default_value = false
BATTLERESULT_DROP_ITEMS_FIELD.default_value = {}
BATTLERESULT_DROP_ITEMS_FIELD.type = 5
BATTLERESULT_DROP_ITEMS_FIELD.cpp_type = 1

BATTLERESULT.name = "BattleResult"
BATTLERESULT.full_name = ".net.BattleResult"
BATTLERESULT.nested_types = {}
BATTLERESULT.enum_types = {}
BATTLERESULT.fields = {BATTLERESULT_HERO_ID_FIELD, BATTLERESULT_DAMAGE_FIELD, BATTLERESULT_WIN_FIELD, BATTLERESULT_DROP_ITEMS_FIELD}
BATTLERESULT.is_extendable = false
BATTLERESULT.extensions = {}

LoginReq = protobuf.Message(LOGINREQ)
BattleResult = protobuf.Message(BATTLERESULT)
