// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Course.Mail
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MailMsg : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static MailMsg GetRootAsMailMsg(ByteBuffer _bb) { return GetRootAsMailMsg(_bb, new MailMsg()); }
  public static MailMsg GetRootAsMailMsg(ByteBuffer _bb, MailMsg obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMailMsg(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MailMsgVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MailMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Sender { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSenderBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSenderBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSenderArray() { return __p.__vector_as_array<byte>(6); }
  public long Gold { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int Items(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ItemsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetItemsBytes() { return __p.__vector_as_span<int>(10, 4); }
#else
  public ArraySegment<byte>? GetItemsBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public int[] GetItemsArray() { return __p.__vector_as_array<int>(10); }
  public bool Read { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Course.Mail.MailMsg> CreateMailMsg(FlatBufferBuilder builder,
      int id = 0,
      StringOffset senderOffset = default(StringOffset),
      long gold = 0,
      VectorOffset itemsOffset = default(VectorOffset),
      bool read = false) {
    builder.StartTable(5);
    MailMsg.AddGold(builder, gold);
    MailMsg.AddItems(builder, itemsOffset);
    MailMsg.AddSender(builder, senderOffset);
    MailMsg.AddId(builder, id);
    MailMsg.AddRead(builder, read);
    return MailMsg.EndMailMsg(builder);
  }

  public static void StartMailMsg(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddSender(FlatBufferBuilder builder, StringOffset senderOffset) { builder.AddOffset(1, senderOffset.Value, 0); }
  public static void AddGold(FlatBufferBuilder builder, long gold) { builder.AddLong(2, gold, 0); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(3, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRead(FlatBufferBuilder builder, bool read) { builder.AddBool(4, read, false); }
  public static Offset<Course.Mail.MailMsg> EndMailMsg(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Course.Mail.MailMsg>(o);
  }
  public static void FinishMailMsgBuffer(FlatBufferBuilder builder, Offset<Course.Mail.MailMsg> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMailMsgBuffer(FlatBufferBuilder builder, Offset<Course.Mail.MailMsg> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MailMsgVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Sender*/, false)
      && verifier.VerifyField(tablePos, 8 /*Gold*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Items*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 12 /*Read*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
