<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Il2CppDummyDll">
      <HintPath>_p31/out/DummyDll/Il2CppDummyDll.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>_p31/out/DummyDll/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Private.CoreLib" />
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>_p31/out/DummyDll/UnityEngine.AndroidJNIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>_p31/out/DummyDll/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>_p31/out/DummyDll/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>_p31/out/DummyDll/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>_p31/out/DummyDll/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>