// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Course.Net
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BattleSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static BattleSync GetRootAsBattleSync(ByteBuffer _bb) { return GetRootAsBattleSync(_bb, new BattleSync()); }
  public static BattleSync GetRootAsBattleSync(ByteBuffer _bb, BattleSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyBattleSync(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, BattleSyncVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BattleSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Course.Net.CmdType Cmd { get { int o = __p.__offset(4); return o != 0 ? (Course.Net.CmdType)__p.bb.GetSbyte(o + __p.bb_pos) : Course.Net.CmdType.Sync; } }
  public uint Frame { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Course.Net.PlayerState? Players(int j) { int o = __p.__offset(8); return o != 0 ? (Course.Net.PlayerState?)(new Course.Net.PlayerState()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PlayersLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public long Seed { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Course.Net.BattleSync> CreateBattleSync(FlatBufferBuilder builder,
      Course.Net.CmdType cmd = Course.Net.CmdType.Sync,
      uint frame = 0,
      VectorOffset playersOffset = default(VectorOffset),
      long seed = 0) {
    builder.StartTable(4);
    BattleSync.AddSeed(builder, seed);
    BattleSync.AddPlayers(builder, playersOffset);
    BattleSync.AddFrame(builder, frame);
    BattleSync.AddCmd(builder, cmd);
    return BattleSync.EndBattleSync(builder);
  }

  public static void StartBattleSync(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddCmd(FlatBufferBuilder builder, Course.Net.CmdType cmd) { builder.AddSbyte(0, (sbyte)cmd, 3); }
  public static void AddFrame(FlatBufferBuilder builder, uint frame) { builder.AddUint(1, frame, 0); }
  public static void AddPlayers(FlatBufferBuilder builder, VectorOffset playersOffset) { builder.AddOffset(2, playersOffset.Value, 0); }
  public static VectorOffset CreatePlayersVector(FlatBufferBuilder builder, Offset<Course.Net.PlayerState>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, Offset<Course.Net.PlayerState>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Course.Net.PlayerState>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePlayersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Course.Net.PlayerState>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPlayersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSeed(FlatBufferBuilder builder, long seed) { builder.AddLong(3, seed, 0); }
  public static Offset<Course.Net.BattleSync> EndBattleSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Course.Net.BattleSync>(o);
  }
  public static void FinishBattleSyncBuffer(FlatBufferBuilder builder, Offset<Course.Net.BattleSync> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedBattleSyncBuffer(FlatBufferBuilder builder, Offset<Course.Net.BattleSync> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class BattleSyncVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Cmd*/, 1 /*Course.Net.CmdType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Frame*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Players*/, Course.Net.PlayerStateVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*Seed*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
