// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Course.Net
{

public enum CmdType : sbyte
{
  Move = 0,
  Attack = 1,
  Skill = 2,
  Sync = 3,
};


}
