// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Course.Net
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static PlayerState GetRootAsPlayerState(ByteBuffer _bb) { return GetRootAsPlayerState(_bb, new PlayerState()); }
  public static PlayerState GetRootAsPlayerState(ByteBuffer _bb, PlayerState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public int Hp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)100; } }
  public int Atk { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)10; } }
  public float Crit { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)1.5f; } }
  public bool Alive { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }
  public Course.Net.Vec2? Pos { get { int o = __p.__offset(16); return o != 0 ? (Course.Net.Vec2?)(new Course.Net.Vec2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Course.Net.PlayerState> CreatePlayerState(FlatBufferBuilder builder,
      int id = 0,
      StringOffset nameOffset = default(StringOffset),
      int hp = 100,
      int atk = 10,
      float crit = 1.5f,
      bool alive = true,
      Offset<Course.Net.Vec2> posOffset = default(Offset<Course.Net.Vec2>)) {
    builder.StartTable(7);
    PlayerState.AddPos(builder, posOffset);
    PlayerState.AddCrit(builder, crit);
    PlayerState.AddAtk(builder, atk);
    PlayerState.AddHp(builder, hp);
    PlayerState.AddName(builder, nameOffset);
    PlayerState.AddId(builder, id);
    PlayerState.AddAlive(builder, alive);
    return PlayerState.EndPlayerState(builder);
  }

  public static void StartPlayerState(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(2, hp, 100); }
  public static void AddAtk(FlatBufferBuilder builder, int atk) { builder.AddInt(3, atk, 10); }
  public static void AddCrit(FlatBufferBuilder builder, float crit) { builder.AddFloat(4, crit, 1.5f); }
  public static void AddAlive(FlatBufferBuilder builder, bool alive) { builder.AddBool(5, alive, true); }
  public static void AddPos(FlatBufferBuilder builder, Offset<Course.Net.Vec2> posOffset) { builder.AddOffset(6, posOffset.Value, 0); }
  public static Offset<Course.Net.PlayerState> EndPlayerState(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Course.Net.PlayerState>(o);
  }
}


static public class PlayerStateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyField(tablePos, 8 /*Hp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Atk*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Crit*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*Alive*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTable(tablePos, 16 /*Pos*/, Course.Net.Vec2Verify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
